platform :ios, '10.0'
use_frameworks!

install! 'cocoapods', :deterministic_uuids => false, :warn_for_multiple_pod_sources => false, :warn_for_unused_master_specs_repo => false

target 'GenericProject' do
    pod 'AFNetworking'
    pod 'SDWebImage'
    pod 'Masonry'
    pod 'SVProgressHUD'
    pod 'IQKeyboardManager'
    pod 'MJRefresh'
    pod 'DZNEmptyDataSet'
    pod 'YYKit'
    pod 'SDCycleScrollView'
    pod 'MBProgressHUD'
    pod 'TABAnimated'
    pod 'BabyBluetooth'
    pod 'MJExtension'
    pod 'WechatOpenSDK'
    pod 'TZImagePickerController'
    pod 'ReactiveObjC'
    pod 'GPUImage'
    pod 'XHLaunchAd'
    pod 'FLAnimatedImage'
    pod "HybridPageKit", :testspecs => ["HybridPageKitTests"]
    pod 'ZLPhotoBrowser'
    pod 'JJCollectionViewRoundFlowLayout'
    pod 'SSZipArchive'
end
